from weasyprint import HTML
from fastapi.responses import StreamingResponse
import io


INVOICE_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12px; color: #1a1a2e; padding: 40px; }}
  .header {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }}
  .org-name {{ font-size: 24px; font-weight: 700; color: #6c63ff; }}
  .org-details {{ font-size: 11px; color: #555; margin-top: 4px; }}
  .doc-title {{ font-size: 28px; font-weight: 300; color: #6c63ff; text-align: right; }}
  .doc-meta {{ text-align: right; font-size: 11px; color: #555; margin-top: 4px; }}
  .section {{ margin-bottom: 24px; }}
  .section-title {{ font-size: 11px; font-weight: 600; color: #888; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }}
  .bill-to {{ font-size: 13px; font-weight: 600; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 8px; }}
  thead th {{ background: #6c63ff; color: white; padding: 10px 8px; text-align: left; font-size: 11px; font-weight: 600; }}
  tbody td {{ padding: 10px 8px; border-bottom: 1px solid #eee; font-size: 12px; }}
  tbody tr:nth-child(even) {{ background: #f9f9ff; }}
  .totals {{ margin-top: 24px; display: flex; justify-content: flex-end; }}
  .totals-table {{ width: 280px; }}
  .totals-table td {{ padding: 5px 8px; font-size: 12px; }}
  .totals-table .total-row td {{ font-size: 14px; font-weight: 700; color: #6c63ff; border-top: 2px solid #6c63ff; padding-top: 8px; }}
  .notes {{ margin-top: 24px; padding: 12px; background: #f5f5ff; border-left: 3px solid #6c63ff; font-size: 11px; color: #555; }}
  .footer {{ margin-top: 40px; text-align: center; font-size: 10px; color: #aaa; }}
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="org-name">{org_name}</div>
      <div class="org-details">GST: {org_gst} | {org_email} | {org_phone}</div>
    </div>
    <div>
      <div class="doc-title">{doc_type}</div>
      <div class="doc-meta">#{doc_number}</div>
      <div class="doc-meta">Date: {doc_date}</div>
      {due_date_html}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Bill To</div>
    <div class="bill-to">{customer_name}</div>
    <div style="font-size:11px;color:#555">{customer_gst_html}</div>
    <div style="font-size:11px;color:#555">{customer_email} | {customer_phone}</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit Price</th>
        <th>GST %</th>
        <th>GST Amt</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      {line_items_html}
    </tbody>
  </table>

  <div class="totals">
    <table class="totals-table">
      <tr><td>Subtotal</td><td style="text-align:right">₹ {subtotal}</td></tr>
      <tr><td>GST</td><td style="text-align:right">₹ {gst_amount}</td></tr>
      <tr class="total-row"><td>Total</td><td style="text-align:right">₹ {total_amount}</td></tr>
    </table>
  </div>

  {notes_html}

  <div class="footer">Generated by Finance & Billing Platform</div>
</body>
</html>
"""


def _build_line_items_html(line_items: list) -> str:
    rows = []
    for i, item in enumerate(line_items, 1):
        rows.append(
            f"<tr><td>{i}</td><td>{item.get('description','')}</td>"
            f"<td>{item.get('quantity','')}</td><td>₹ {item.get('unit_price','')}</td>"
            f"<td>{item.get('gst_rate','')}%</td><td>₹ {item.get('gst_amount','')}</td>"
            f"<td>₹ {item.get('line_total','')}</td></tr>"
        )
    return "".join(rows)


def generate_pdf(data: dict) -> bytes:
    """Render a PDF for an invoice or quotation and return bytes."""
    line_items_html = _build_line_items_html(data.get("line_items", []))
    notes_html = f'<div class="notes"><strong>Notes:</strong> {data.get("notes","")}</div>' if data.get("notes") else ""
    due_date_html = f'<div class="doc-meta">Due: {data.get("due_date","")}</div>' if data.get("due_date") else ""
    customer_gst_html = f'GST: {data.get("customer_gst","")}' if data.get("customer_gst") else ""

    html_content = INVOICE_TEMPLATE.format(
        org_name=data.get("org_name", ""),
        org_gst=data.get("org_gst", "N/A"),
        org_email=data.get("org_email", ""),
        org_phone=data.get("org_phone", ""),
        doc_type=data.get("doc_type", "INVOICE"),
        doc_number=data.get("doc_number", ""),
        doc_date=data.get("doc_date", ""),
        due_date_html=due_date_html,
        customer_name=data.get("customer_name", ""),
        customer_gst_html=customer_gst_html,
        customer_email=data.get("customer_email", ""),
        customer_phone=data.get("customer_phone", ""),
        line_items_html=line_items_html,
        subtotal=data.get("subtotal", "0.00"),
        gst_amount=data.get("gst_amount", "0.00"),
        total_amount=data.get("total_amount", "0.00"),
        notes_html=notes_html,
    )
    return HTML(string=html_content).write_pdf()


def pdf_streaming_response(pdf_bytes: bytes, filename: str) -> StreamingResponse:
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
